# Generated by Django 6.0.4 on 2026-04-25 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 25, 2, 57, 17, 584997, tzinfo=datetime.timezone.utc)),
        ),
    ]
