# Generated by Django 6.0.5 on 2026-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_alter_account_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refferal_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='refferal_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
