# Generated by Django 6.0.5 on 2026-06-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_account_refferal_amount_account_refferal_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='refferal_amount',
            new_name='referral_amount',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='refferal_count',
            new_name='referral_count',
        ),
    ]
