# Generated by Django 6.0.5 on 2026-06-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0015_alter_account_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='referral_amount',
            new_name='total_referral_amount',
        ),
    ]
