# Generated by Django 6.0.5 on 2026-06-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_rename_referral_amount_account_total_referral_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referral_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_referral_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
