# Generated by Django 6.0.5 on 2026-05-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
