# Generated by Django 6.0.5 on 2026-05-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_wishlist_options_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('partially_cancel', 'Partially Cancelled'), ('returned', 'Returned'), ('partially_returned', 'Partially Returned')], default='pending', max_length=20),
        ),
    ]
