# Generated by Django 6.0.5 on 2026-05-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='value',
            new_name='discount_value',
        ),
    ]
