# Generated by Django 6.0.5 on 2026-06-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='target_type',
        ),
    ]
