# Generated by Django 6.0.5 on 2026-06-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_offer_options_variant_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='offer',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon'),
        ),
    ]
