# Generated by Django 6.0.5 on 2026-06-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_cart_coupon_order_coupon_order_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('partially_cancelled', 'Partially Cancelled'), ('cancelled', 'Cancelled'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
