# Generated by Django 6.0.5 on 2026-05-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_orderitem_cancelled_at_orderitem_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_cancelled',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cancelled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
