# Generated by Django 6.0.5 on 2026-06-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_offer_category_offer_min_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_level',
            new_name='offer_type',
        ),
    ]
