# Generated by Django 6.0.5 on 2026-06-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_offer_level_offer_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20),
        ),
    ]
