# Generated by Django 6.0.5 on 2026-06-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_order_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
