# Generated by Django 6.0.5 on 2026-06-16 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_offer_options_offer_category_offer_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.offer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
