# Generated by Django 6.0.5 on 2026-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_order_offer_orderitem_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
