# Generated by Django 6.0.5 on 2026-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_orderitem_coupon_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon_snapshot',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='offer_snapshot',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_discount_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_no',
            field=models.IntegerField(null=True),
        ),
    ]
