# Generated by Django 6.0.5 on 2026-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_orderitem_coupon_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='offer_no',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
