# Generated by Django 6.0.5 on 2026-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_orderitem_offer_no_order_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
