# Generated by Django 6.0.5 on 2026-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_order_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_paid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
