# Generated by Django 6.0.5 on 2026-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_wallettransaction_order_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='target_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category')], default='product', max_length=20),
        ),
    ]
