# Generated by Django 6.0.5 on 2026-07-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_offer_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='target_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category')], max_length=20),
        ),
    ]
