# Generated by Django 6.0.5 on 2026-07-07 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_offer_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='category_image'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='variant_image'),
        ),
    ]
