# Generated by Django 6.0.5 on 2026-07-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_category_image_alter_variantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('partially_cancelled', 'Partially Cancelled'), ('returned', 'Returned'), ('partially_returned', 'Partially Returned')], default='pending', max_length=20),
        ),
    ]
