# Generated by Django 6.0.4 on 2026-04-22 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 16, 47, 55, 825512, tzinfo=datetime.timezone.utc)),
        ),
    ]
