# Generated by Django 6.0.4 on 2026-04-22 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_otp_expires_at_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='address_type',
            new_name='address_label',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 17, 13, 51, 141392, tzinfo=datetime.timezone.utc)),
        ),
    ]
