# Generated by Django 6.0.4 on 2026-04-23 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_address_type_addresses_address_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 4, 6, 50, 137986, tzinfo=datetime.timezone.utc)),
        ),
    ]
