# Generated by Django 6.0.4 on 2026-04-23 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_addresses_address_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 4, 25, 22, 406822, tzinfo=datetime.timezone.utc)),
        ),
    ]
