# Generated by Django 6.0.4 on 2026-04-23 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_id_addresses_user_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 4, 29, 44, 965704, tzinfo=datetime.timezone.utc)),
        ),
    ]
