# Generated by Django 6.0.4 on 2026-04-24 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_addresses_user_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 24, 10, 21, 53, 824557, tzinfo=datetime.timezone.utc)),
        ),
    ]
