# Generated by Django 6.0.4 on 2026-04-24 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 24, 10, 23, 18, 369929, tzinfo=datetime.timezone.utc)),
        ),
    ]
