# Generated by Django 6.0.5 on 2026-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
